version: "3.8"
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  mysql:
    image: mysql
    restart: always
    user: "${UID}:${GID}"
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=example_development
    - MYSQL_ROOT_HOST=%
  rabbitmq:
    image: rabbitmq:management
    ports:
    - "5672:5672"
    - "15672:15672"